feat: added quality code scripts and fixed spelling errors.

diff --git a/app/sdms-v4/.husky/commit-msg b/app/sdms-v4/.husky/commit-msg
--- a/app/sdms-v4/.husky/commit-msg
+++ b/app/sdms-v4/.husky/commit-msg
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/bin/bash
 #  ***************************************************************************
 #  Copyright 2017 - 2023, Schlumberger
 #
@@ -15,13 +15,17 @@
 #  limitations under the License.
 #  ***************************************************************************
 
-. "$(dirname "$0")/_/husky.sh"
-
-cd ./app/sdms-v4 
 
 printf "\n%s\n" "-------------------------------------------------------"
-echo "5 - validate commit message"
+echo "validate commit message sdms"
 printf "%s\n" "-------------------------------------------------------"
-npx --no-install commitlint --edit $1
-printf "\n%s\n%s\n" "> Commit message compliant"
-printf "%s\n\n" "-------------------------------------------------------"
+
+mex=$(cat $1)
+REGEX="^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_\/¯)(\(\w+\))?(!)?(: (.*\s*)*))|(Merge (.*\s*)*)"
+if [[ ! "$mex" =~ $REGEX ]]; then
+    printf "%s\n" "ERROR: the commit message need to follow the conventional commits syntax"
+    printf "%s\n" "https://github.com/conventional-changelog/commitlint/#what-is-commitlint"
+    exit 1
+else
+    printf "%s\n" "commit message compliant with commitlint syntax"
+fi
